### ISSUE TITLE
cant acces the web page 

### ISSUE THREAD

**Issue by jamestristan121** [WiIIiam278/SchematicUpload#6]
ever time i run the command to use the uploader and click the link i get a line of text that says 
źš{"translate":"disconnect.genericReason","with":["Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 69 out of bounds for length 1"]} 
ive try everthing to fix it nothing works

**Comment by WiIIiam278** [comment]
What version of Minecraft is your server on and what client are you using? And what's the value of your chat links setting in your client chat options?

**Comment by jamestristan121** [comment]
> What version of Minecraft is your server on and what client are you using? And what's the value of your chat links setting in your client chat options?

im on 1.19.2 im useing the fether client witch uses fabric i dont know where to find the value for the chat links

**Comment by jamestristan121** [comment]
i didnt want to cloes sorry

**Comment by WiIIiam278** [comment]
I think this is caused by the client you're using here. Try with a vanilla client

**Comment by WiIIiam278** [comment]
Caused by MineDown's component serializer not being updated for the client's version. Have moved to adventure-platform-bukkit and will keep this up-to-date for each version going forward.
